version: "3.9"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./mariadb
    expose:
      - 3306
    networks:
      - my_net
    volumes:
      - vol_mariadb:${DB_PATH}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
      - WORDPRESS_DATABASE_USER=${WORDPRESS_DATABASE_USER}
      - WORDPRESS_DATABASE_PASS=${WORDPRESS_DATABASE_PASS}
  # nginx:
  # wordpress:


#docker volume
volumes:
  vol_mariadb:
    name: vol_mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_HOST_VOL_MARIADB}

#custom network
networks:
  my_net:
    name: my_net
    driver: bridge
