version: "3.9"

services:

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./mariadb
    expose:
      - 3306
    networks:
      - my_net
    volumes:
      - vol_mariadb:${DB_PATH}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
      - WORDPRESS_DATABASE_USER=${WORDPRESS_DATABASE_USER}
      - WORDPRESS_DATABASE_PASS=${WORDPRESS_DATABASE_PASS}

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "443:443"
    networks:
      - my_net
    volumes:
      - vol_wordpress:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
      - nginx
    build:
      context: ./wordpress
    networks:
      - my_net
    expose:
      - 9000
    volumes:
      - vol_wordpress:${WP_PATH}
    restart: always
    environment:
      - WP_PATH=${WP_PATH}
      - WORDPRESS_URL=${WORDPRESS_URL}
      - WORDPRESS_SITE_TITLE=${WORDPRESS_SITE_TITLE}
      - WORDPRESS_ADMIN_NAME=${WORDPRESS_ADMIN_NAME}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD}


#docker volume
volumes:
  vol_mariadb:
    name: vol_mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_HOST_VOL_MARIADB}
  vol_wordpress:
    name: vol_wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PATH_HOST_VOL_WORDPRESS}

#custom network
networks:
  my_net:
    name: my_net
    driver: bridge
